version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: aidd-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: aidd
      POSTGRES_PASSWORD: aidd_dev_password
      POSTGRES_DB: aidd
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aidd -d aidd"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
