"""initial schema: conversations, user_messages, llm_responses

Revision ID: 0f132edeb3b2
Revises: 
Create Date: 2025-10-16 15:07:58.704177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f132edeb3b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_table('llm_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_responses_conversation_id', 'llm_responses', ['conversation_id'], unique=False)
    op.create_index('idx_llm_responses_is_deleted', 'llm_responses', ['is_deleted'], unique=False)
    op.create_table('user_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_messages_conversation_id', 'user_messages', ['conversation_id'], unique=False)
    op.create_index('idx_user_messages_is_deleted', 'user_messages', ['is_deleted'], unique=False)
    op.create_index('idx_user_messages_user_id', 'user_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_messages_user_id', table_name='user_messages')
    op.drop_index('idx_user_messages_is_deleted', table_name='user_messages')
    op.drop_index('idx_user_messages_conversation_id', table_name='user_messages')
    op.drop_table('user_messages')
    op.drop_index('idx_llm_responses_is_deleted', table_name='llm_responses')
    op.drop_index('idx_llm_responses_conversation_id', table_name='llm_responses')
    op.drop_table('llm_responses')
    op.drop_index('idx_conversations_user_id', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
