name: Quality Checks

on:
  push:
    branches: [ main, develop, day03-refactor ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv venv
        . .venv/bin/activate
        uv pip install aiogram openai python-dotenv
        uv pip install ruff mypy pytest pytest-asyncio pytest-cov aiosqlite
        uv pip install -e .

    - name: Format check
      run: |
        . .venv/bin/activate
        ruff format src/ --check

    - name: Lint check
      run: |
        . .venv/bin/activate
        ruff check src/

    - name: Type check
      run: |
        . .venv/bin/activate
        mypy src/

    - name: Run tests with coverage
      run: |
        . .venv/bin/activate
        pytest tests/ -v --cov=src --cov-report=term-missing --cov-report=xml

    - name: Upload coverage to Codecov (optional)
      uses: codecov/codecov-action@v4
      if: false  # Отключено по умолчанию, включить при наличии Codecov токена
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
